Homework lesson-10 level-3 task-10
konstantins-buts/jg-java-1-online-spring-thursday-2021 pull request #1110
Opened 2021-08-18 15:54 UTC by WoDees

2021-08-18 16:37 UTC, daniilsjb requested changes

2021-08-18 16:37 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_10/level_3/task_10/InMemoryProductRepository.java
> +        return null;
Вместо `null` нужно возвращать `Optional.empty()`. Вся фишка класса `Optional` в том, что он позволяет нам избавиться от нуллов 🙂

2021-08-18 16:37 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_10/level_3/task_10/ProductRepositoryDemo.java
> +}
Для этих репозиторий стоит также писать автоматические тесты, и желательно покрывать больше сценариев. Например, если бы в репозитории не было продукта `"Apple"`, то этот код бы кинул `NullPointerException`, даже несмотря на вызов `orElse`. Вы можете догадаться о причине 🙃

2021-08-18 17:23 UTC, WoDees commented on src/main/java/students/igors_raginskis/lesson_10/level_3/task_10/ProductRepositoryDemo.java
> +}
Как раз-таки не догадываюсь, потому что ничего не понял про Optional. Попробую что-то сделать...

2021-08-19 10:40 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_10/level_3/task_10/ProductRepositoryDemo.java
> +}
Это было связано с тем, что метод `findByTitle` возвращал `null` вместо пустого `Optional`. Если попытаться вызвать любой метод на нулле, программа крашнется с ошибкой. То есть до `orElse` даже не доходило в тех случаях, где продукта в репозитории нет.

2021-08-19 10:40 UTC, daniilsjb approved these changes
👍

2021-08-19 10:40 UTC, merged