Homework lesson-10 level-5 task-18
konstantins-buts/jg-java-1-online-spring-thursday-2021 pull request #1125
Opened 2021-08-20 13:57 UTC by WoDees

2021-08-20 14:11 UTC, daniilsjb requested changes

2021-08-20 14:11 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_10/level_5/task_18/BookReaderImpl.java
> +    }
В задании требуется поиск по книгам, у которых имя автора начинается с "букв, указанных пользователем". О названии книги речи не идёт. По сути вместо `equals` достаточно использовать метод [`startsWith`](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#startsWith(java.lang.String)). Тогда получится такое условие:

```java
if (book != null && book.getAuthor().startsWith(keyword)) {
    ...
}
```

Касаемо наименований, можно также вдохновиться самой библиотекой Java и вместо `keyword` использовать слово prefix. Тогда можно назвать `findByAuthorPrefix`, например. 🙂

2021-08-20 14:11 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_10/level_5/task_18/BookReaderImplTest.java
> +        assertEqualBook(expected, actual, scenarioDescription);
Соответственно, этот сценарий составлен не так, как требуется. Нужно составить несколько книг, у которых автор начинается с одной и той же последовательности букв, и убедиться, что все они были возвращены при использовании нового метода. Например, вот так:

```java
Book book1 = new Book("A Game of Thrones", "George Martin");
Book book2 = new Book("A Clash of Kings", "George Martin");
Book book3 = new Book("1984", "George Orwell");
 // книга, которая намерено не попадает под критерий
Book book4 = new Book("The C Programming Language", "Kernighan & Ritchie");

Book[] expected = {book1, book2, book3};
Book[] actual = bookReader.findByAuthorPrefix("George");
assertEqualBook(expected, actual, scenarioDescription);
```

2021-08-20 14:21 UTC, WoDees commented on src/main/java/students/igors_raginskis/lesson_10/level_5/task_18/BookReaderImpl.java
> +    }
я неправильно понял задание. Думал, что надо будет найти по ключевому слову автора или название. Отсюда keyword

2021-08-20 17:15 UTC, WoDees reviewed
Исправил всё в 20 таске

2021-08-21 14:42 UTC, daniilsjb approved these changes

2021-08-21 14:42 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_10/level_5/task_18/BookReaderImpl.java
> +                }
Я же подсказал, что здесь стоит использовать `startsWith`. Он будет работать для любой последовательности символов, а не только для слов, разделённых пробелами.

2021-08-21 14:42 UTC, merged