Lesson 7: Task 1.
konstantins-buts/jg-java-1-online-spring-thursday-2021 pull request #1174
Opened 2021-08-27 12:49 UTC by SergejsZaharenko

Не могу никуда дальше продвинуться, хотел изначально посчитать количество слов и записать эти значения в массив или хешмапу, дабы вызывать сами слова по их индексу. Что нужно изменить, чтобы программа заработала? Читаемый ли код? Очень нужна ваша консультация.

2021-08-28 20:38 UTC, daniilsjb requested changes
Понимаю, задание нелёгкое. Я понимаю намерение вашего кода, хотя его стоило бы отформатировать, даже если он реализован не до конца.

Концептуально задачу можно разделить на три шага:
- разбить текст на слова;
- посчитать частоту каждого слова;
- найти наибольшую частоту и вернуть связанное с ней слово.

У каждой операции есть ввод и вывод:
- String → String[]
- String[] → Map<String, Integer>
- Map<String, Integer> → String

И потому всю программу можно реализовать из нескольких методов, каждый из которых реализует одну часть задачи. Ниже привожу более конкретное описание этих действий 🙂

2021-08-28 20:38 UTC, daniilsjb commented on src/main/java/students/sergejs_zaharenko/lesson_7/task_1/WordService.java
> +    }
Начём с первого: нам нужно разделить исходную строку на набор отдельных слов. Метод `split` принимает т.н. регулярное выражение. Я не буду подробно описывать здесь то, как они работают (хотя это весьма интересная и очень глубокая тема), но просто дам совет: лучше всего разделять слова выражением `\\W+`. По сути оно находит последовательности символов, которые не могут быть частью слова (пунктуация и пробелы). Если интересно, можете поиграться с [вот этим](https://regexr.com/) инструментом.

Также дам ещё один совет: прежде, чем разбивать текст на слова, используйте метод `trim`. Он обрезает все пробелы в начале и в конце строки. Иначе в конечный массив могут затисаться всякие пустые строки 😄

Этот метод также стоит сделать приватным, поскольку он является лишь деталью реализации класса `WordService`.

В конечном итоге этот код может выглядеть так:

```java
private String[] splitWords(String text) {
    return text.toLowerCase().trim().split("\\W+");
}
```

2021-08-28 20:38 UTC, daniilsjb commented on src/main/java/students/sergejs_zaharenko/lesson_7/task_1/WordService.java
> +    }
Следующий шаг: считаем количество каждого слова в массиве. Действительно, для такой операции есть много способов, но поскольку вы выбрали подход с хэшмапой, то я пройдусь конкретно по нему.

На самом деле ваш метод работает почти правильно, но есть пара нюансов. Во-первых, я не советую хранить `wordToCount` в качестве свойства, поскольку иначе записанные в нём значения будут сохранены между разными вызовами `findMostFrequentWord`. Гораздо проще будет просто возвращать новую мапу с нуля. Во-вторых, поиск наиболее популярного слова стоит выделить как отдельную операцию.

Вот как можно переписать этот метод:

```java
private Map<String, Integer> countWords(String[] words) {
    Map<String, Integer> result = new HashMap<>();
    for (String word : words) {
        if (result.containsKey(word)) {
            result.put(word, result.get(word) + 1);
        } else {
            result.put(word, 1);
        }
    }
    return result;
}
```

Заметьте, что он снова приватный. На самом деле можно сделать этот код гораздо короче, если воспользоваться специальным методом [`compute`](https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#compute-K-java.util.function.BiFunction-):

```java
private Map<String, Integer> countWords(String[] words) {
    Map<String, Integer> result = new HashMap<>();
    for (String word : words) {
        result.compute(word, (k, v) -> (v == null) ? 1 : v + 1);
    }
    return result;
}
```

По сути эта лямбда делает то же самое, что и написанный вручную код: если значения ещё нет, то задаётся один, иначе в качестве нового значения задаётся старое, увеличенное на единицу.

2021-08-28 20:38 UTC, daniilsjb commented on src/main/java/students/sergejs_zaharenko/lesson_7/task_1/WordService.java
> +        }
Теперь остаётся последняя операция: поиск самого популярного слова. Здесь нет ничего особенно нового, но я воспользуюсь парой хитрых конструкций:

```java
private String findKeyWithHighestValue(Map<String, Integer> wordCount) {
    String bestKey = null;
    Integer bestValue = 0;

    for (var entry : wordCount.entrySet()) {
        if (entry.getValue() > bestValue) {
            bestKey = entry.getKey();
            bestValue = entry.getValue();
        }
    }

    return bestKey;
}
```

Во-первых, нас интересует `entrySet`, а не `keySet`, поскольку нам нужно знать количество каждого слово, чтобы найти самое частое. Во-вторых, я использую ключевое слово `var`, которое означает, что компилятор может сам распознать тип данных для переменной `entry`. Указывать его вручную было бы неудобно, поскольку он слишком длинный.

Дам пару примеров использования `var`, чтобы стало понятней:

```java
// Компилятор понимает, что эта переменная имеет тип String.
var string = "Hello, world!";

// Компилятор понимает, что эта переменная имеет тип Long.
var number = 1L;

// Компилятор понимает, что эта переменная имеет тип Boolean.
var number = true;

// Компилятор понимает, что эта переменная имеет тип List<String>.
var list = List.of("a", "b", "c");
```

2021-08-28 20:38 UTC, daniilsjb commented on src/main/java/students/sergejs_zaharenko/lesson_7/task_1/WordService.java
> +    }
Теперь мы можем объединить все методы, написанные ранее, в целостную реализацию:

```java
public String findMostFrequentWord(String text) {
    var words = splitWords(text);
    var wordCount = countWords(words);
    return findKeyWithHighestValue(wordCount);
}
```

Я схитрил и снова использовал `var`, чтобы код выглядел немного красивее. Заметьте, что с точки зрения программы `words` действительно имеет тип `String[]`, а `wordCount` действительно `Map<String, Integer>`. Просто нам не нужно было указывать это вручную!

2021-09-18 14:20 UTC, SergejsZaharenko commented
Извините, за эту вакханалию, что я устроил в этой ветке, были проблемы с Git'ом. Вот сам коммит с выполненым заданием. 64bb0b78c26df16aa75f12cff94d325f05fdd1a3

2021-09-19 11:39 UTC, daniilsjb approved these changes

2021-09-19 11:39 UTC, merged