Homework Lesson_2 Level_1 Task_2
konstantins-buts/jg-java-1-online-spring-thursday-2021 pull request #16
Opened 2021-05-30 16:29 UTC by SWONNANT

2021-05-31 16:53 UTC, daniilsjb requested changes

2021-05-31 16:53 UTC, daniilsjb commented on src/main/java/students/timur_pogorelov/lesson_2/level_1/task_2/Solution2.java
> +            double secondDoubleNumber = scanner.nextInt();
Всё правильно, но нужно обязательно использовать `scanner.nextDouble()`, иначе пользователь не может вводить вещественные числа 😄

2021-06-01 07:51 UTC, SWONNANT commented on src/main/java/students/timur_pogorelov/lesson_2/level_1/task_2/Solution2.java
> +            double secondDoubleNumber = scanner.nextInt();
Благодарю! Исправил.

2021-06-01 09:58 UTC, daniilsjb approved these changes
👍

2021-06-01 09:58 UTC, merged