Homework Lesson-3 level-5 task-21
konstantins-buts/jg-java-1-online-spring-thursday-2021 pull request #194
Opened 2021-06-09 13:42 UTC by WoDees

2021-06-09 15:22 UTC, daniilsjb requested changes
Та же проблема, это не продолжение предыдущих заданих. Нет метода `voice`, нет других свойств. 😅

2021-06-22 19:55 UTC, daniilsjb approved these changes
Ещё есть пара неточностей, но я их прощаю - с точки зрения логики всё выполнено верно. Тем не менее я очень сильно прошу, пишите решение каждого таска в **своей** папке. То есть `lesson_3/level_5/task_21` отдельно от `lesson_3/level_5/task_20` и прочих.

Дело в том, что сейчас все ваши последующие решения тасков переписывают предыдущие, поскольку в каждом PR эти два файла (`Dog.java` и `DogDemo.java`) находятся в одном и том же месте (с точки зрения git вы коммитите одни и те же два файла, хотя это решения разных тасков).

В таких случаях мне приходится решать конфликты на GitHub, выбирая, какие изменения оставить, а какие нет. Здесь это ещё не так страшно, поскольку каждое из этих заданий основывается на предыдущих, но лучше решения всё же изолировать.

2021-06-22 19:55 UTC, daniilsjb commented on src/main/java/students/artiom_mshar/lesson_3/level_5/Dog.java
> +    }
Здесь тоже стоит принимать имя в конструкторе, но да ладно.

2021-06-22 19:55 UTC, daniilsjb commented on src/main/java/students/artiom_mshar/lesson_3/level_5/DogDemo.java
> +        dog.changeColor("Yellow");
Стоит сначала менять цвет, а потом уже подавать голос. Тогда можно увидеть, что изменения действительно отразились.

2021-06-22 19:57 UTC, merged

2021-06-23 09:39 UTC, WoDees commented
Я сам не понимаю, что там  где закоммитилось, потому что больше половины
бранчей у меня нет в идее. И если по ним переходить, то там неразбериха
какая-то. Я пытался поудалять в них то, что было и сделать задания по новой

вт, 22 июн. 2021 г. в 22:55, Daniils Buts ***@***.***>:

> ***@***.**** approved this pull request.
>
> Ещё есть пара неточностей, но я их прощаю - с точки зрения логики всё
> выполнено верно. Тем не менее я очень сильно прошу, пишите решение каждого
> таска в *своей* папке. То есть lesson_3/level_5/task_21 отдельно от
> lesson_3/level_5/task_20 и прочих.
>
> Дело в том, что сейчас все ваши последующие решения тасков переписывают
> предыдущие, поскольку в каждом PR эти два файла (Dog.java и DogDemo.java)
> находятся в одном и том же месте (с точки зрения git вы коммитите одни и те
> же два файла, хотя это решения разных тасков).
>
> В таких случаях мне приходится решать конфликты на GitHub, выбирая, какие
> изменения оставить, а какие нет. Здесь это ещё не так страшно, поскольку
> каждое из этих заданий основывается на предыдущих, но лучше решения всё же
> изолировать.
> ------------------------------
>
> In src/main/java/students/artiom_mshar/lesson_3/level_5/Dog.java
> <https://github.com/konstantins-buts/jg-java-1-online-spring-thursday-2021/pull/194#discussion_r656532610>
> :
>
> > +    public Dog(int age, String color) {
> +        this.age = age;
> +        this.color = color;
> +    }
>
> Здесь тоже стоит принимать имя в конструкторе, но да ладно.
> ------------------------------
>
> In src/main/java/students/artiom_mshar/lesson_3/level_5/DogDemo.java
> <https://github.com/konstantins-buts/jg-java-1-online-spring-thursday-2021/pull/194#discussion_r656533037>
> :
>
> > +        dog.voice();
> +        dog.changeColor("Yellow");
>
> Стоит сначала менять цвет, а потом уже подавать голос. Тогда можно
> увидеть, что изменения действительно отразились.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/konstantins-buts/jg-java-1-online-spring-thursday-2021/pull/194#pullrequestreview-689935393>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQUTSYRNR5ESPVZTUXOZPK3TUDTDJANCNFSM46MCHRNA>
> .
>