Homework Lesson-3 level-7 task-28
konstantins-buts/jg-java-1-online-spring-thursday-2021 pull request #198
Opened 2021-06-09 14:37 UTC by WoDees

2021-06-09 15:27 UTC, daniilsjb requested changes
Небольшая ошибка, но всё же несоответствие с заданием. Тем не менее респект за то, что правильно реализовали метод `actualPrice` - это здесь самое сложное 😎

2021-06-09 15:27 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_3/level_7/Product.java
> +    }
Вот очень близко, но наоборот 😅

Имя нужно указывать в конструкторе, и это должен быть единственный его параметр. То есть строку "Delorean" нужно указывать уже в `ProductDemo`. Цену и скидку же нужно указывать вне конструктора через точку (см. ниже).

2021-06-09 15:27 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_3/level_7/ProductDemo.java
> +         car.printInformation();
Этот код должен выглядеть так:

```java
Product car = new Product("Delorean");
car.regularPrice = 599.5;
car.discount = 30.0;
car.printInformation();
```

2021-06-09 18:08 UTC, WoDees commented
Отвечу на все ваши замечания тут. Если бы я понимал, что от меня хотят, то
проблем с выполнением заданий не было. Я 80% времени от всей длмашки ломаю
голову над тем, что надо выполнить((. А с заданиями, в которых был класс
Dog, я сначала не понял, что это продолжения одного и того же задания, да и
с комитами я там намудрил, поэтому нн стал исправлять. С учетом всех
ошибок, следующая домашка должна быть проколов😅

ср, 9 июн. 2021 г., 18:28 Daniils Buts ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Небольшая ошибка, но всё же несоответствие с заданием. Тем не менее
> респект за то, что правильно реализовали метод actualPrice - это здесь
> самое сложное 😎
> ------------------------------
>
> In src/main/java/students/igors_raginskis/lesson_3/level_7/Product.java
> <https://github.com/konstantins-buts/jg-java-1-online-spring-thursday-2021/pull/198#discussion_r648423740>
> :
>
> > +    String name = "Delorean";
> +    double regularPrice;
> +    double discount;
> +
> +    public Product(double regularPrice, double discount) {
> +        this.regularPrice = regularPrice;
> +        this.discount = discount;
> +
> +    }
>
> Вот очень близко, но наоборот 😅
>
> Имя нужно указывать в конструкторе, и это должен быть единственный его
> параметр. То есть строку "Delorean" нужно указывать уже в ProductDemo.
> Цену и скидку же нужно указывать вне конструктора через точку (см. ниже).
> ------------------------------
>
> In
> src/main/java/students/igors_raginskis/lesson_3/level_7/ProductDemo.java
> <https://github.com/konstantins-buts/jg-java-1-online-spring-thursday-2021/pull/198#discussion_r648424415>
> :
>
> > +         Product car = new Product(599.5,30.0);
> +         car.printInformation();
>
> Этот код должен выглядеть так:
>
> Product car = new Product("Delorean");
> car.regularPrice = 599.5;
> car.discount = 30.0;
> car.printInformation();
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/konstantins-buts/jg-java-1-online-spring-thursday-2021/pull/198#pullrequestreview-679813243>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQUTSYSLCYKATAIYDIDXMALTR6CATANCNFSM46MFXG7Q>
> .
>

2021-06-09 18:19 UTC, daniilsjb commented
Понимаю, домашки составлены странновато. Иногда стоит сразу посмотреть все домашки за левел и понять, связаны они или нет. Если вначале сказано «продолжение», значит каждое задание должно отталкиваться от предыдущего. На нашей стороне мы обдумываем как можно сделать их понятнее 🙂

Если возникают вопросы, не стесняйтесь писать в Telegram, можно мне лично 👍

2021-06-24 12:22 UTC, daniilsjb approved these changes

2021-06-24 12:22 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_3/level_7/Product.java
> +    double actualPrice;
Этому классу свойство `actualPrice` не нужно, эта информация высчитывается по запросу.

2021-06-24 12:22 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_3/level_7/Product.java
> +        return this.actualPrice = this.regularPrice - this.regularPrice * (this.discount / 100);
Следовательно, присвоение тут лишнее.

2021-06-24 12:22 UTC, merged