HomeWork lesson 3 level 7 task 28
konstantins-buts/jg-java-1-online-spring-thursday-2021 pull request #213
Opened 2021-06-09 19:36 UTC by Hidra90

finish

2021-06-10 15:29 UTC, daniilsjb requested changes

2021-06-10 15:29 UTC, daniilsjb commented on src/main/java/students/Anton_Harbuz/lesson_3/level_7/task_28/Product.java
> +        this.discount = discountProduct;
Всё очень хорошо, но небольшое несоответствие с условием задания. Метод `actualPrice` не должен принимать в качестве параметров `regularPriceProduct` и `discountProduct` - _они уже должны быть свойствами на момент вызова этого метода_.

На данный момент может казаться, что разницы в том, откуда исходят эти данные, нет. В будущем вы больше узнаете о дизайне объектно-ориентированного кода и сможете понять почему это важно, но если вкратце, то менять состояние объекта `Product` выходит для пределы обязанностей этого метода.

2021-06-10 15:29 UTC, daniilsjb commented on src/main/java/students/Anton_Harbuz/lesson_3/level_7/task_28/ProductDemo.java
> +        product.actualPrice(300, 30);
В целом вы можете уже видеть, почему это плохая идея. Информацию о продукте нужно вывести через метод `printInformation`, но чтобы его вызвать, нужно сначало задать цену и скидку. Для этого вы вызываете метод подсчёта цены, который это делает (хотя и не должен), а непосредственно основной результат операции - настоящую цену - просто игнорируете.

Конечный же код должен выглядеть примерно так:

```java
Product product = new Product("Telic");
product.regularPrice = 300.0;
product.discount = 30.0;
product.printInformation();
```

Надеюсь "придирка" понятна 🙂

2021-06-12 13:24 UTC, Hidra90 commented on src/main/java/students/Anton_Harbuz/lesson_3/level_7/task_28/Product.java
> +        this.discount = discountProduct;
исправил, но не понятно так или нет, и не понятно зачем, ведь задача такая :
2. Название продукта нужно задавать через конструктор, а стоимость и скидку через оператор ".".

2021-06-12 15:42 UTC, daniilsjb commented on src/main/java/students/Anton_Harbuz/lesson_3/level_7/task_28/Product.java
> +        this.discount = discountProduct;
Теперь стало правильно. Я уже ниже объяснил, зачем это нужно - чтобы разделить логику подсчёта цены от инициализации данных о продукте.

2021-06-12 15:43 UTC, daniilsjb approved these changes
👍

2021-06-12 15:43 UTC, merged