Lesson 3: Task 21 completed.
konstantins-buts/jg-java-1-online-spring-thursday-2021 pull request #297
Opened 2021-06-13 21:36 UTC by SergejsZaharenko

Выполнено 21 задание 3 урока.

2021-06-14 11:34 UTC, daniilsjb requested changes

2021-06-14 11:34 UTC, daniilsjb commented on src/main/java/students/sergejs_zaharenko/lesson_3/level_5/task_21/Dog.java
> +    }
Не совсем правильная реализация метода. Здесь нужно только принимать параметр `String newColour` и сразу его назначить свойству `this.colour`. С точки зрения собаки нет значения, откуда берётся этот цвет - из консоли, из файла, обычной строки в коде, и т.д. Поэтому эту деталь следует оставить методу `main`.

2021-06-14 11:34 UTC, daniilsjb commented on src/main/java/students/sergejs_zaharenko/lesson_3/level_5/task_21/Dog.java
> +        int dogAgeBirthday = dogAge + 1;
Здесь ошибка из предыдущего задания касаемо возраста собаки.

2021-06-15 11:59 UTC, SergejsZaharenko commented
Переделал 21 задание, но до сих пор не уверен, правильно ли.

2021-06-15 12:40 UTC, daniilsjb requested changes

2021-06-15 12:40 UTC, daniilsjb commented on src/main/java/students/sergejs_zaharenko/lesson_3/level_5/task_21/Dog.java
> +    }
Здесь всё ещё не так. По сути метод должен выглядеть примерно так:

```java
void changeColour(String newColour) {
    // заменить свойство colour на newColour
}
```

2021-06-15 12:40 UTC, daniilsjb commented on src/main/java/students/sergejs_zaharenko/lesson_3/level_5/task_21/DogDemo.java
> +        dog1.changeColour();
Тогда логику чтения цвета из консоли нужно полностью перенести сюда.

2021-06-17 15:26 UTC, daniilsjb approved these changes
👍

2021-06-17 15:26 UTC, daniilsjb commented on src/main/java/students/sergejs_zaharenko/lesson_3/level_5/task_21/DogDemo.java
> +        dog1.changeColour(scanner1.next());
По идее здесь можно переиспользовать уже существующий сканнер 🙃

2021-06-17 15:26 UTC, merged