Homework Lesson-4 - level -6 task-16
konstantins-buts/jg-java-1-online-spring-thursday-2021 pull request #312
Opened 2021-06-14 17:33 UTC by WoDees

Бью рекорды, на этот раз день ушёл. В примере этого задания описана переменная String priceInformation = google.getPriceInformation();

Как сделать метод, чтобы потом его вывести в переменную можно было? В этом случае будет распечатана информация. Я как не пытался, не смог этого добиться

2021-06-15 12:25 UTC, daniilsjb requested changes
Нужно признать, это задание достаточно сложное, далеко не все его обычно выполняют на этом уровне. Так что, как говорится, [моё увожение](https://www.memesmonkey.com/images/memesmonkey/fb/fbcd0daaa6f74b3a7c13bec6c3cd684e.jpeg). 😎

Но косяк с `getStockInformation` нужно исправить. Главное помнить, что строки - это просто объекты. Их тоже можно сохранять в переменные, передавать в качестве параметров и возвращать из функций. При составлении методов главное правильно продумать сигнатуру - тип возвращаемых данных и параметров, дальше компилятор сам наругает 😄

2021-06-15 12:25 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_4/level_6/Stock.java
> +    }
Всё очень просто - нужно просто эту строку вернуть 😄

```java
String getStockInformation() {
    return "Company = " + companyName + ", Current Price = " + currentPrice + ", Min Price = " + minPrice + ", Max Price = " + maxPrice;
}
```

Строчка получается очень длиная, её ещё можно разбить. Например вот так:

```java
String getStockInformation() {
    return "Company = " + companyName + ", "
        + "Current Price = " + currentPrice + ", "
        + "Min Price = " + minPrice + ", "
        + "Max Price = " + maxPrice;
}
```

Этот недочёт нужно исправить, поскольку целью метода всё-таки является вернуть конечную строку, а не вывести её на экран. Это то, что подразумевается под словом `get`.

2021-06-15 12:25 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_4/level_6/StockTest.java
> +    }
В этих тестах есть ещё альтернативный подход. Можно проверять не индивидуальные свойства объекта, а целиком его статусную строку:

```java
public void stockTest1() {
    Stock stock = new Stock("Apple", 15);
    stock.updatePrice(12);
    stock.updatePrice(11);
    stock.updatePrice(23);

    String actual = stock.getStockInformation();
    String expected = "Company = Apple, Current Price = 23, Min Price = 11, Max Price = 23";

    if (actual.equals(expected)) {
        System.out.println("[OK]");
    } else {
        System.out.println("[ERROR]");
    }
}
```

Я бы даже сказал, что возможно этот вариант правильнее, поскольку он проверяет, что строка формируется правильно. А лучше всего сделать оба вида тестов - один со свойствами и несколько со строками.

2021-06-15 15:10 UTC, WoDees commented on src/main/java/students/igors_raginskis/lesson_4/level_6/StockTest.java
> +    }
Я путаюсь в правильности записи, поэтому сделал всё отдельно. Разве ИДЕЯ поймет, что есть что, если записать вот так?    String expected = "Company = Apple, Current Price = 23, Min Price = 11, Max Price = 23";

2021-06-15 15:29 UTC, WoDees commented on src/main/java/students/igors_raginskis/lesson_4/level_6/StockTest.java
> +    }
Буду стараться. У меня итак голова опухла, когда выполнял это задание. Рисовал там что-то в пейнте :D
[https://cdn.discordapp.com/attachments/362621245176676352/854381958363742228/unknown.png](url)

2021-06-15 16:09 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_4/level_6/StockTest.java
> +    }
Nice 🤣

Только вот мне кажется, вы удалили файл Stock.java с решением этого задания 🤔 Если это было по ошибке, то можете просто заново есть создать, скопировав содержимое [отсюда](https://github.com/konstantins-buts/jg-java-1-online-spring-thursday-2021/pull/312/commits/677b0ad533e624051c4c4986f552a6bbecb0fe2e).

2021-06-22 11:13 UTC, WoDees commented on src/main/java/students/igors_raginskis/lesson_4/level_6/StockTest.java
> +    }
ой, да, вроде что-то не так сделал. Как восстановить? Я перехожу по ссылке, но ничего такого не могу найти, чтобы восстановить файл

2021-06-22 14:01 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_4/level_6/StockTest.java
> +    }
Там должна быть большая синяя надпись `Load diff`. Если кликнуть по ней, то можно увидеть содержимое того файла.

2021-06-22 14:08 UTC, WoDees commented on src/main/java/students/igors_raginskis/lesson_4/level_6/StockTest.java
> +    }
да, я увидел. А восстановить как?

2021-06-22 15:21 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_4/level_6/StockTest.java
> +    }
Проще всего будет заново создать файл, скопировать туда содержимое и закоммитить. Этого можно также добиться через комманды git, но на это можно много времени потратить 😁

2021-06-22 19:31 UTC, daniilsjb approved these changes
👍

2021-06-22 19:32 UTC, merged