Homework Lesson-5 level-4 task-29
konstantins-buts/jg-java-1-online-spring-thursday-2021 pull request #404
Opened 2021-06-23 00:38 UTC by WoDees

2021-06-24 12:48 UTC, daniilsjb requested changes

2021-06-24 12:48 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_5/level_4/ArrayEvenNumbers.java
> +                System.out.print("[" + evenNumber + "] ");
Отсутствие фигурных скобок в телах `if`/`else`, циклов и прочего карается смертной казнью ☠ Хотя Java это и позволяет (из соображений того, что это упрощает грамматику языка), это очень плохой стиль - такой код гораздо труднее читать и расширять. Нужно переписать так:

```java
for (int number : numbers) {
    if (number % 2 == 0) {
        System.out.print("[" + number + "]");
    }
}
```

Обратите внимание, что имя `number` подходит лучше. Мы ещё не знаем, чётное оно или нет - на этом этапе это просто число из массива.

2021-06-24 13:15 UTC, WoDees commented on src/main/java/students/igors_raginskis/lesson_5/level_4/ArrayEvenNumbers.java
> +                System.out.print("[" + evenNumber + "] ");
Идея предложила упросить, а я даже и не знал, что они там должны быть. Сейчас всё будет)

2021-06-24 13:36 UTC, daniilsjb requested changes
Это странно, вероятно у вас неправильно настроена стилистика кода в идее 🤔 Мне она такого никогда не предлагала.

2021-06-24 13:36 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_5/level_4/ArrayEvenNumbers.java
> +        for (int number : numbers)
После `for` всё ещё нет фигурных скобок 🙃

2021-06-25 10:21 UTC, daniilsjb approved these changes
👍

2021-06-25 10:21 UTC, merged