Lesson 6: Task 7 completed.
konstantins-buts/jg-java-1-online-spring-thursday-2021 pull request #714
Opened 2021-07-08 13:14 UTC by SergejsZaharenko

Выполнено 7 задание 6 урока.
Долго думал, как выполнить это задание. Не знаю, насколько корректно я его выполнил :D

2021-07-08 13:56 UTC, SergejsZaharenko commented
Оказывается, что остальные задания 2 уровня, это продолжение реализации этого. Я могу чуть позже переделать это задание в соответствии с тем, как просилось. :D

2021-07-11 14:40 UTC, daniilsjb requested changes
Задания второго уровня составлены странновато, так что разрешаю их всех выполнить одним заходом 😉

2021-07-11 14:40 UTC, daniilsjb commented on src/main/java/students/sergejs_zaharenko/lesson_6/level_2/task_7/DayOfTheWeekDetectorDemo.java
> +                = scanner.nextInt();
Здесь не нужен разрыв строки. Также, здесь не нужно свойство `dayNumber` - достаточно вернуть прочитанное сканнером число.

2021-07-11 14:40 UTC, daniilsjb commented on src/main/java/students/sergejs_zaharenko/lesson_6/level_2/task_7/DayOfTheWeekDetectorDemo.java
> +    }
Вам не нужно использовать свойство класса `dayOfTheWeek`. Этот метод должен только возвращать строку исходя из номера дня, то есть `return "Monday"` и т.д. более чем достаточно.

К слову, в задании предлагается использовать особую форму `switch`-выражения. Смысл в том, что этот оператор возвращает значение выбранной ветки, из-за чего его можно напрямую вернуть из метода:

```java
String findDayOfTheWeek(int dayNumber) {
    return switch (dayNumber) {
        case 1 -> "Monday";
        case 2 -> "Tuesday";
        ...
        default -> "Not correct day number";
    };
}
```
Это называется switch-expresssion.

2021-07-11 14:40 UTC, daniilsjb commented on src/main/java/students/sergejs_zaharenko/lesson_6/level_2/task_7/DayOfTheWeekDetectorTest.java
> +    }
Отличная идея! Могу порекомендовать небольшое упрощение. Этому методу нет особого смысла принимать параметр `caseAmount`, поскольку ему следует просто проверить все кейсы. Также, массив `cases` можно убрать, заменив его на простой индекс в цикле:

```java
void createCases() {
    DayOfTheWeekDetectorDemo dayOfTheWeekDetectorDemo = new DayOfTheWeekDetectorDemo();
    String[] expectedResults = {"Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday", "Not correct day number"};

    for (int i = 0; i < 7; i++) {
        String realResult = dayOfTheWeekDetectorDemo.findDayOfTheWeek(i + 1);
        String expectedResult = expectedResults[i];
        if (realResult.equals(expectedResult)) {
            System.out.println("[Day detector test: " + expectedResult + " = OK]");
        } else {
            System.out.println("[Day detector test: " + expectedResult + " = FAIL]");
        }
    }
}
```

2021-08-19 21:05 UTC, daniilsjb approved these changes

2021-08-19 21:05 UTC, merged