Homework Lesson 6 Level 3 Task 17
konstantins-buts/jg-java-1-online-spring-thursday-2021 pull request #748
Opened 2021-07-12 14:11 UTC by KirillPrihodjko

Homework Lesson 6 Level 3 Task 17

2021-07-12 17:07 UTC, daniilsjb requested changes
Сортировку нужно реализовать вручную, но придумывать алгоритм не нужно. Можете подсмотреть в интернете пример реализации простого алгоритма bubble sort, [как здесь](https://www.programiz.com/dsa/bubble-sort).

2021-07-12 17:07 UTC, daniilsjb commented on src/main/java/students/kirill_prihodjko/lesson_6/level_3/task_17/ArrayService.java
> +     int[] sort(int[] array) {
Этот метод не должен что-либо возвращать.

2021-07-12 20:21 UTC, KirillPrihodjko commented on src/main/java/students/kirill_prihodjko/lesson_6/level_3/task_17/ArrayService.java
> +     int[] sort(int[] array) {
А как сделать тесты если метод void? Мне Idea предлагает заменить void на int[] !

2021-07-13 09:59 UTC, daniilsjb commented on src/main/java/students/kirill_prihodjko/lesson_6/level_3/task_17/ArrayService.java
> +     int[] sort(int[] array) {
Создаёте массив с какими-то числами, сортируете, и через `Arrays.equals` проверяете обновлённое содержимое массива:

```java
int[] actual = { 7, 4, 9, 2, 13, 5 };
int[] expected = { 2, 4, 5, 7, 9, 13 };

ArrayService service = new ArrayService();
service.sort(actual);

if (Arrays.equals(actual, expected)) {
    // тест прошёл успешно...
} else {
    // тест провалился...
}
```

2021-07-13 14:28 UTC, daniilsjb requested changes

2021-07-13 14:28 UTC, daniilsjb commented on src/main/java/students/kirill_prihodjko/lesson_6/level_3/task_17/ArrayService.java
> +         Arrays.sort(array);
Ещё раз, сортировку нужно реализовать вручную. Я дал выше ссылку на статью с подробно описанным и самым простым алгоритмом 🙂

2021-07-13 18:59 UTC, daniilsjb approved these changes

2021-07-13 18:59 UTC, merged