Homework Lesson-6 level-3 task-17
konstantins-buts/jg-java-1-online-spring-thursday-2021 pull request #785
Opened 2021-07-17 20:09 UTC by WoDees

2021-07-18 11:05 UTC, daniilsjb requested changes

2021-07-18 11:05 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_6/level_3/task_17/ArrayService.java
> +    }
Сортировку нужно реализовать самому. Можете найти в интернете информацию про алгоритм bubble sort и реализовать его (он самый простой). Обязательно убедитесь, что ваш код правильно оформлен.

2021-07-18 11:05 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_6/level_3/task_17/ArrayServiceTest.java
> +        System.out.println("Result is: " + Arrays.equals(expected, array));
Не хватает вызова `assertEqual`.

2021-07-19 18:55 UTC, daniilsjb requested changes

2021-07-19 18:55 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_6/level_3/task_17/ArrayService.java
> +    }
Реализовано правильно, но не хватает фигурных скобок вокруг каждого цикла. Поэтому я и говорил, проследите за оформлением кода - в интернете можно найти всякое 🙂

2021-07-19 18:55 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_6/level_3/task_17/ArrayServiceTest.java
> +        System.out.println("Result is: " + Arrays.equals(expected, array));
Всё ещё нет вызова `assertEqual`.

2021-07-22 17:35 UTC, WoDees commented on src/main/java/students/igors_raginskis/lesson_6/level_3/task_17/ArrayServiceTest.java
> +        System.out.println("Result is: " + Arrays.equals(expected, array));
Не видел вроде в задании, что обязательно надо вызывать именно этот метод. Так же проще, но ладно

2021-08-03 17:06 UTC, WoDees commented
а где тут ошибка? Я вроде исправил всё

2021-08-03 17:51 UTC, WoDees commented
Либо Вы неправильно увидели, где я написал это, либо ошибка какая-то. У меня висит не закрытый бранч 
Homework Lesson-6 level-3 task-17

2021-08-03 17:53 UTC, daniilsjb approved these changes
Либо я что-то не заметил, либо github не оповестил меня об изменениях. Выглядит правильно 👍

2021-08-03 17:54 UTC, merged

2021-08-03 17:54 UTC, WoDees commented
даа, вот, а то уже пару недель висит это задание. И я тут писал, а не там. Спасибо!