Homework Lesson-6 level-4 task-20
konstantins-buts/jg-java-1-online-spring-thursday-2021 pull request #788
Opened 2021-07-17 23:45 UTC by WoDees

2021-07-18 11:06 UTC, daniilsjb requested changes

2021-07-18 11:06 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_6/level_4/ForLoopContinue.java
> +             if (i == 3){
Что-то тут не до конца отформатированный код 🤔

2021-07-19 16:38 UTC, WoDees commented on src/main/java/students/igors_raginskis/lesson_6/level_4/ForLoopContinue.java
> +             if (i == 3){
![изображение](https://user-images.githubusercontent.com/69810530/126195613-f427e8ee-52f8-4f4e-ba5f-14283f6f9a7e.png)

2021-07-19 18:56 UTC, daniilsjb approved these changes
👍

2021-07-19 18:56 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_6/level_4/ForLoopContinue.java
> +             if (i == 3){
Выглядит зачётно, ничего не могу сказать 😁

2021-07-19 18:56 UTC, merged