Homework Lesson-6 level-5 task-26
konstantins-buts/jg-java-1-online-spring-thursday-2021 pull request #847
Opened 2021-07-22 17:33 UTC by WoDees

2021-07-22 19:16 UTC, WoDees commented
Не обращайте внимания, пожалуйста на переменные, которые в начале класса TicTacToe, я пытался сделать крестики нолики

2021-07-23 11:43 UTC, daniilsjb requested changes
Нужно исправить ошибку предыдущих заданий, а также отформатировать код.

2021-07-23 11:43 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_6/level_5/task_26/TicTacToe.java
> +            }
Во внутренних циклах более читабельно (как мне кажется) использовать классический `for` цикл с индексом:

```java
for (int i = 0; i < field.length; i++) {
    for (int j = 0; j < field[i].length; j++) {
        if (field[i][j] == -1) {
            return false;
        }
    }
}
```

2021-07-23 11:43 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_6/level_5/task_26/TicTacToeTest.java
> +                         {1, 1, 0}};
Неправильно отформатировано. Стоит писать так:

```java
int[][] array = {
    {1, 0, 1},
    {0, 0, 1},
    {1, 1, 0},
};
```

2021-07-23 13:46 UTC, WoDees commented on src/main/java/students/igors_raginskis/lesson_6/level_5/task_26/TicTacToeTest.java
> +                         {1, 1, 0}};
хорошо, учту

2021-07-24 10:07 UTC, daniilsjb approved these changes
👍

2021-07-24 10:07 UTC, merged