Homework Lesson-6 level-6 task-32
konstantins-buts/jg-java-1-online-spring-thursday-2021 pull request #852
Opened 2021-07-22 20:59 UTC by WoDees

2021-07-23 12:02 UTC, daniilsjb requested changes

2021-07-23 12:02 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_6/level_7/task_32/FizzBuzzTest.java
> +    }
Строки нужно сравнивать через `equals`. Поскольку в каждом тесте сраниваются именно строки, рекомендую переписать сам метод `assertEqual` так, чтобы он принимать и сравнивал две строки, а не `boolean`.

2021-07-23 12:02 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_6/level_7/task_32/FizzBuzzTest.java
> +        assertEqual(expected, actual == fizzBuzz, "unDiv");
Может лучше проверить, что `FizzBuzz(20)` равен `"20"`? 😁

2021-07-23 13:49 UTC, WoDees commented on src/main/java/students/igors_raginskis/lesson_6/level_7/task_32/FizzBuzzTest.java
> +        assertEqual(expected, actual == fizzBuzz, "unDiv");
на всякий случай написал

2021-07-23 13:51 UTC, WoDees commented on src/main/java/students/igors_raginskis/lesson_6/level_7/task_32/FizzBuzzTest.java
> +    boolean expected = true;
ну я подумал, что лучше было бы вывести отдельную переменную и вызывать её, нежели создавать её снова в каждом методе. Не? :D

2021-07-24 10:36 UTC, daniilsjb commented on src/main/java/students/igors_raginskis/lesson_6/level_7/task_32/FizzBuzzTest.java
> +    boolean expected = true;
С одной стороны да, но свойства немного круче обычных переменных, поскольку распространяются на весь класс - даже там, где не надо. Если какому-то тесту нужно, чтобы `expected` был `false`, то всё равно пришлось бы создавать локальную переменную. Но почему тогда отдавать предпочтение именно `true`?

Это приводит и к тому моменту, что один из тестов может изменить значение `expected` на `false`, и тесты, которые ожидают `true`, провалились бы. Всегда плохо, когда тесты зависят от какого-то общего состояния. Если бы речь шла о каком-то stateless классе, то каких проблем бы не возникало.

Ну и в конечном итоге, константы `true` и `false` в крайнем случае можно писать и без лишних переменных, уж целое свойство для них будет жирновато :)

2021-07-24 10:37 UTC, daniilsjb approved these changes
👍

2021-07-24 10:37 UTC, merged