Homework Lesson 8 Level 5 Task 25
konstantins-buts/jg-java-1-online-spring-thursday-2021 pull request #902
Opened 2021-07-28 16:32 UTC by KirillPrihodjko

2021-07-28 19:52 UTC, daniilsjb requested changes

2021-07-28 19:52 UTC, daniilsjb commented on src/main/java/students/kirill_prihodjko/lesson_8/level_5/task_25/Shapes.java
> +    }
Вам не нужно создавать свой массив, он уже был передан в качестве параметра 😄 Вам нужно пройти по этому массиву, посчитать площадь каждой фигуры через метод `shape.area()`, и сложить их все вместе.

2021-08-01 13:15 UTC, daniilsjb requested changes

2021-08-01 13:15 UTC, daniilsjb commented on src/main/java/students/kirill_prihodjko/lesson_8/level_5/task_25/Shapes.java
> +    }
Этот код посчитает площадь только первой фигуры. Объявление и возвращение переменной `sum` должны находится за пределами цикла, внутри должен быть только код `sum += shape.calculateArea()`.

2021-08-01 15:46 UTC, KirillPrihodjko commented on src/main/java/students/kirill_prihodjko/lesson_8/level_5/task_25/Shapes.java
> +    }
Добрый вечер, а чтобы посчитать площадь каждой фигуры, что для этого нужно сделать никак не могу понять?(    
Написать 4 раза shape.calculateArea(); ?

2021-08-01 17:04 UTC, KirillPrihodjko commented on src/main/java/students/kirill_prihodjko/lesson_8/level_5/task_25/Shapes.java
> +    }
Добрый вечер, а чтобы посчитать площадь каждой фигуры, что для этого нужно сделать никак не могу понять?(
Написать 4 раза shape.calculateArea(); ?

2021-08-01 17:29 UTC, daniilsjb commented on src/main/java/students/kirill_prihodjko/lesson_8/level_5/task_25/Shapes.java
> +    }
```java
double area(Shape[] shapes) {
    double sum = 0.0;
    for (Shape shape : shapes) {
        sum += shape.calculateArea();
    }
    return sum;
}
```

Никаких "4 раза", считать площадь нужно ровно столько раз, сколько есть фигур в массиве - для этого и используется цикл. Если у вас есть тест, в котором передаётся четыре фигуры, это ещё не значит, что их всегда будет четыре.

2021-08-01 18:33 UTC, daniilsjb approved these changes
😎👍

2021-08-01 18:33 UTC, merged